### ISSUE TITLE
target-stitch -n does not validate the presence of keys

### ISSUE THREAD

**Issue by pedromachados** [singer-io/target-stitch#12]
I am developing a tap to push data to Stitch. When I run target-stitch with the -n option it completes fine. However, when I pushed the data to Stitch, I got an error saying keys were missing. It would be nice for the -n option to do as much validation as possible.

**Comment by karstendick** [comment]
@pedromachados Good idea. I've fixed this in https://github.com/singer-io/target-stitch/pull/13
