### ISSUE TITLE
State output not possible / conflicts with tap-github

### ISSUE THREAD

**Issue by sminnee** [singer-io/target-stitch#48]
I can't get useful state data out of this target, meaning that incremental uploads of taps isn't working. In my case I'm working with https://github.com/singer-io/tap-github/

The getting started guide recommends that you pipe stdout from the target into a state file, and take the last line. target-stitch seems to recommend instead that you use `-o filename.json`, which is fine, but the docs are out of date.

The output produced appears to have 1 line per data-type (in my case: assignees, collaborators, stargazers, issues). I would need to retain the read-state for _each_ of these.

```
{"table_name": "assignees", ...}
{"table_name": "collaborators", ...}
{"table_name": "stargazers", ...}
{"table_name": "issues", ...}
```

Reading the code for tap-github, it seems to be looking for quite a different format for the statefile than what is produced by target-stitch. It's not clear which package is in violation of the spec. tap-github seems to expect a key "issues" with a timestamp of the last imported issue.

```
def get_all_issues(schema, config,  state):
    '''
    https://developer.github.com/v3/issues/#list-issues-for-a-repository
    '''
    repo_path = config['repository']
    if 'issues' in state and state['issues'] is not None:
        query_string = '&since={}'.format(state['issues'])
    else:
        query_string = ''
```

**Comment by briansloane** [comment]
Closing this in favor of the referenced issue on `tap-github`.
